executable = conda_wrapper_fine.sh

LOGFILE = "finetuning"

EXTRA_ARGS   =                                # blank on purpose
arguments    = python finetuning_skip.py $(EXTRA_ARGS)
# arguments  = python finetuning_skip.py

output     = logs_finetuning/$(LOGFILE).out
error      = logs_finetuning/$(LOGFILE).err
log        = logs_finetuning/$(LOGFILE).log
getenv     = True


Requirements = CUDADriverVersion >= 12.0

+request_gpus = 1
#request_cpus   = 1
#request_memory = 32 GB



#queue 31
#Requirements = TARGET.vm_name == "its-u20-nfs-20210413" && regexp("CRUSH", TARGET.name) 
queue 
